spring:
  application:
    name: stock-service
  datasource:
    url: "${DB_URL:jdbc:postgresql://localhost:5435/orbenox}"
    username: "${DB_USERNAME:postgres}"
    password: "${DB_PASSWORD:postgres}"
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true
      pool-name: OrbenoxHikariPool
  rabbitmq:
    port: 5673
