spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  cache:
    type: NONE
  cloud:
    discovery:
      enabled: false

eureka:
  client:
    enabled: false

app:
  jwtSecretKey: "test-jwt-secret-key-for-integration-tests"
  jwtExpiration: "86400000"
