spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  cache:
    type: NONE
  cloud:
    discovery:
      enabled: false

eureka:
  client:
    enabled: false

app:
  jwtSecretKey: "${JWT_SECRET_KEY:0e1156ac32b34087c0fc3da6b5cc015e1d86f013acdfc1bbbed78940f1d8c81d}"
  jwtExpiration: "${JWT_EXPIRATION:86400000}"
