INSERT INTO user_type (code, name, created_by)
VALUES ('ADMIN', 'Administrators', 'system'),
       ('USER', 'Ordinary users', 'system'),
       ('GUEST', 'Guests', 'system');

INSERT INTO action (code, name, created_by)
VALUES ('READ', 'Action for read permission', 'system'),
       ('CREATE', 'Action for object editing permission', 'system'),
       ('UPDATE', 'Action for object editing permission', 'system'),
       ('DELETE', 'Action for object deleting permission', 'system'),
       ('APPROVE', 'Action for order approve', 'system'),
       ('REJECT', 'Action for order reject', 'system'),
       ('CLOSE', 'Action for order close', 'system');

INSERT INTO unit_dimension (code, name, created_by)
VALUES ('COUNT', 'Say', 'system'),
       ('MASS', 'Kütlə', 'system'),
       ('LENGTH', 'Uzunluq', 'system'),
       ('VOLUME', 'Həcm', 'system'),
       ('TEMPERATURE', 'Temperatur', 'system');

INSERT INTO unit (code, unit_dimension_id, base, factor_to_base, offset_to_base, name, created_by)
VALUES ('PCS', 1, TRUE, 1, 0, 'Ədəd', 'system'),
       ('KG', 2, FALSE, 1000, 0, 'Kiloqram', 'system'),
       ('G', 2, TRUE, 1, 0, 'Qram', 'system'),
       ('M', 3, TRUE, 1, 0, 'Metr', 'system'),
       ('L', 4, TRUE, 1, 0, 'Litr', 'system'),
       ('M3', 4, FALSE, 1000, 0, 'Kub metr', 'system'),
       ('C', 5, TRUE, 1, 0, 'Selsi', 'system'),
       ('K', 5, FALSE, 1, -273.15, 'Kelvin', 'system'),
       ('F', 5, FALSE, 5 / 9, 0, 'Farenheyt', 'system');

INSERT INTO currency (code, name, created_by)
VALUES ('AZN', 'Manat', 'system'),
       ('USD', 'Dollar', 'system'),
       ('EUR', 'Avro', 'system'),
       ('RUB', 'Rubl', 'system');

INSERT INTO country (code, name, created_by)
VALUES ('AZ', 'Azərbaycan', 'system'),
       ('TR', 'Türkiyə', 'system'),
       ('RU', 'Rusiya', 'system'),
       ('CH', 'Çin', 'system'),
       ('US', 'ABŞ', 'system'),
       ('EN', 'İngiltərə', 'system'),
       ('DE', 'Almaniya', 'system'),
       ('FR', 'Fransa', 'system'),
       ('IT', 'İtaliya', 'system'),
       ('ES', 'İspaniya', 'system');

INSERT INTO resource (code, name, created_by)
VALUES ('LOOKUP', 'Baxış', 'system'),
       ('APP_USER', 'İstifadəçilər', 'system'),
       ('APP_ROLE', 'Rollar', 'system'),
       ('APP_PERMISSION', 'İcazələr', 'system'),
       ('APP_USER_ROLE', 'İstifadəçi rolları', 'system'),
       ('ACTION', 'Əməliyyatlar', 'system'),
       ('RESOURCE', 'Obyektlər', 'system'),
       ('CURRENCY', 'Valyutalar', 'system'),
       ('UNIT', 'Ölçü vahidləri', 'system'),
       ('UNIT_DIMENSION', 'Kəmiyyətlər', 'system'),
       ('COUNTRY', 'Ölkələr', 'system'),
       ('BRAND', 'Brendlər', 'system'),
       ('PRODUCER', 'İstehsalçılar', 'system'),
       ('PRODUCT_TYPE', 'Mal tipləri', 'system'),
       ('PRODUCT_CLASS', 'Mal sinifləri', 'system'),
       ('PRODUCT_GROUP', 'Mal qrupları', 'system'),
       ('PRODUCT_CATEGORY', 'Mal kateqoriyarları', 'system'),
       ('PRICE', 'Qiymət növləri', 'system'),
       ('WAREHOUSE', 'Anbarlar', 'system'),
       ('PRODUCT', 'Mallar', 'system'),
       ('PRODUCT_PRICE', 'Mal qiymətləri', 'system'),
       ('PRODUCT_BARCODE', 'Mal barkodları', 'system'),
       ('PRODUCT_UNIT', 'Mal üzrə ölçü vahidləri', 'system'),
       ('PRODUCT_WAREHOUSE', 'Mal-anbar', 'system');

INSERT INTO resource_action (resource_id, action_id, created_by)
VALUES (1, 1, 'system'),
       (2, 1, 'system'),
       (2, 2, 'system'),
       (2, 3, 'system'),
       (2, 4, 'system'),
       (3, 1, 'system'),
       (3, 2, 'system'),
       (3, 3, 'system'),
       (3, 4, 'system'),
       (4, 1, 'system'),
       (4, 2, 'system'),
       (4, 3, 'system'),
       (4, 4, 'system'),
       (5, 1, 'system'),
       (5, 2, 'system'),
       (5, 3, 'system'),
       (5, 4, 'system'),
       (6, 1, 'system'),
       (6, 2, 'system'),
       (6, 3, 'system'),
       (6, 4, 'system'),
       (7, 1, 'system'),
       (7, 2, 'system'),
       (7, 3, 'system'),
       (7, 4, 'system'),
       (8, 1, 'system'),
       (8, 2, 'system'),
       (8, 3, 'system'),
       (8, 4, 'system'),
       (9, 1, 'system'),
       (9, 2, 'system'),
       (9, 3, 'system'),
       (9, 4, 'system'),
       (10, 1, 'system'),
       (10, 2, 'system'),
       (10, 3, 'system'),
       (10, 4, 'system'),
       (11, 1, 'system'),
       (11, 2, 'system'),
       (11, 3, 'system'),
       (11, 4, 'system'),
       (12, 1, 'system'),
       (12, 2, 'system'),
       (12, 3, 'system'),
       (12, 4, 'system'),
       (13, 1, 'system'),
       (13, 2, 'system'),
       (13, 3, 'system'),
       (13, 4, 'system'),
       (14, 1, 'system'),
       (14, 2, 'system'),
       (14, 3, 'system'),
       (14, 4, 'system'),
       (15, 1, 'system'),
       (15, 2, 'system'),
       (15, 3, 'system'),
       (15, 4, 'system'),
       (16, 1, 'system'),
       (16, 2, 'system'),
       (16, 3, 'system'),
       (16, 4, 'system'),
       (17, 1, 'system'),
       (17, 2, 'system'),
       (17, 3, 'system'),
       (17, 4, 'system'),
       (18, 1, 'system'),
       (18, 2, 'system'),
       (18, 3, 'system'),
       (18, 4, 'system'),
       (19, 1, 'system'),
       (19, 2, 'system'),
       (19, 3, 'system'),
       (19, 4, 'system'),
       (20, 1, 'system'),
       (20, 2, 'system'),
       (20, 3, 'system'),
       (20, 4, 'system'),
       (21, 1, 'system'),
       (21, 2, 'system'),
       (21, 3, 'system'),
       (21, 4, 'system'),
       (22, 1, 'system'),
       (22, 2, 'system'),
       (22, 3, 'system'),
       (22, 4, 'system'),
       (23, 1, 'system'),
       (23, 2, 'system'),
       (23, 3, 'system'),
       (23, 4, 'system'),
       (24, 1, 'system'),
       (24, 2, 'system'),
       (24, 3, 'system'),
       (24, 4, 'system');

